plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compress-images

# Site settings
# title: Rebecca & Ryan
# email: nathan@nathanorick.com
# url: http://wedding.nathanorick.com
# description: "We're getting married and can't wait to celebrate with you!"
# baseurl: "/weddings/sample"

collections:
  stories:
    sort_by: order
  modals:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml

compress_images:
  images_path: "{assets,photos}/**/*.{gif,png,jpg,jpeg,svg}"
